# Generated by Django 3.0.7 on 2020-08-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedsTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
