# Generated by Django 3.0.7 on 2020-08-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20200801_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedsTitles',
            new_name='FeedTitle',
        ),
    ]
