# Generated by Django 3.0.7 on 2020-08-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20200801_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedTitle',
        ),
    ]
