# Generated by Django 3.0.7 on 2020-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, unique=True)),
                ('acc_id', models.CharField(default='00000000', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('twitter_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('twitter_user', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField(default='Some text of twitter')),
                ('release_date', models.DateField()),
                ('hash_tags', models.TextField(null=True)),
            ],
        ),
    ]
