# Generated by Django 3.0.7 on 2020-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='hash_tags',
            field=models.TextField(null=True),
        ),
    ]
