# Generated by Django 3.0.7 on 2020-08-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='twitter_user',
            field=models.CharField(max_length=200),
        ),
    ]
