# Generated by Django 3.0.7 on 2020-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20200814_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='text',
            field=models.TextField(default='Some text of twitter'),
        ),
    ]
